# Generated by Django 5.0.2 on 2024-07-22 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextExtractor', '0003_alter_fileupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='coordinates_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='image_file',
            field=models.FileField(default='default_coordinates.txt', upload_to=''),
        ),
    ]
